version: '3'

volumes:
  minio_data:
    driver: local

services:

  mail_reader:
    image: 'mail-reader:latest'
    build:
      context: .
    container_name: mail-reader
    ports:
      - "8090:8090"
    depends_on:
      rabbitMQ:
        condition: service_started
      minio:
        condition: service_started
    environment:
      - MAIL_HOST=
      - MAIL_USERNAME=
      - MAIL_PASSWORD=
      - SPRING_RABBITMQ_HOST=rabbitMQ
      - SPRING_RABBITMQ_USERNAME=admin
      - SPRING_RABBITMQ_PASSWORD=admin
      - MINIO_BUCKET_NAME=mail
      - MINIO_USERNAME=admin
      - MINIO_PASSWORD=admin123456
      - MINIO_HOST=minio
      - MAIL_CHECK_INTERVAL=* * 0 * * *

  rabbitMQ:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - 5672:5672
      - 15672:15672

  minio:
    image: docker.io/bitnami/minio:2023
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/bitnami/minio/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123456
