version: '3'

volumes:
  minio_data:
    driver: local

services:

  rabbitMQ:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - 5672:5672
      - 15672:15672

  minio:
    image: docker.io/bitnami/minio:2023
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/bitnami/minio/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123456
